### ISSUE TITLE
build failed in macos mojave and ubuntu 18.04 

### ISSUE THREAD

**Issue by ShiauweiZhao** [kevinmehall/nano-dm#4]
```error: failed to run custom build command for `libusb-sys v0.2.3`
process didn't exit successfully: `/Users/xiaowei/src/nano-dm/target/release/build/libusb-sys-948f381eeeb5fdfc/build-script-build` (exit code: 101)
--- stderr
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: "Failed to run `\"pkg-config\" \"--libs\" \"--cflags\" \"libusb-1.0\"`: No such file or directory (os error 2)"', libcore/result.rs:1009:5
note: Run with `RUST_BACKTRACE=1` for a backtrace.```
how to do with this ?
@kevinmehall  thanks

**Comment by kevinmehall** [comment]
The key part is `Failed to run \"pkg-config\" \"--libs\" \"--cflags\" \"libusb-1.0\": No such file or directory (os error 2)"'`. You need to install libusb-1.0, see the README.
